### PR TITLE
Use airline for cmdline parsing

### PR DESCRIPTION
**Pull request by justinpitts**
This should provide a command-line with the same functionality as with arg4j, using Airline.

There's much to do of course WRT adding help descriptions, etc.

As far as exception handling goes, I simply wrapped in RuntimeException and rethrew - let me know if you need something else here.

### CODE REVIEW

**Comment by eevans** [comment]
I just wanted to drop a quick note to say that I haven't had the chance to look at this yet; Real Life has gotten the best of me recently, but I haven't forgotten it is here.

I'll circle back to this RSN; Thanks Justin!

**Comment by justinpitts** [comment]
No worries. Let me know if it needs any changes.

**Comment by justinpitts** [comment]
Hey just wanted to touch base and make sure you didn't have any questions or concerns about these changes.

**Comment by eevans** [comment]
It looks good; Thanks Justin

Sorry it took me so long (I have no excuse)!

**Pull request merged**
